version: "3.4"

services:
  core:
    build:
      context: ../..
      dockerfile: Dockerfile
      target: builder
    container_name: core
    command:  "sh -c \"cd app && fresh\" "
    volumes:
      - ../..:/my-simple-all-chat
    ports:
      - "10180:880"
    environment:
      POSTGRES_HOST: postgres
      POSTGRES_PORT: 5432
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: mypass
      POSTGRES_DB: simple_chat

  postgres:
    image: postgres:11
    container_name: postgres
    volumes:
      - ./postgres/initdb.sh:/docker-entrypoint-initdb.d/initdb.sh
      - ./postgres/db:/var/lib/postgresql/data
    restart: always
    ports:
      - "5432:5432"
        
  postgres-adminer:
    image: adminer
    container_name: adminer
    restart: always
    ports:
      - "8080:8080"
    logging:
      driver: none